#!/usr/bin/env python3
# -*- coding: utf-8 -*-

'''Manages API authentication with JWT (that are generated by the frontend)'''

##-Imports
from flask import request, jsonify
from functools import wraps
import jwt

import os
from dotenv import load_dotenv


##-Init
# Construct the path to the .env file in the parent directory
dotenv_path = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 
    '.env'
)
# Load the .env file from the parent directory
load_dotenv(dotenv_path)

SECRET_KEY = os.environ.get('JWT_SHARED_TOKEN')


##-Decoder
def decode_token() -> dict[str, str]:
    '''
    Tries to decode the token and return its content.

    Out:
        payload     if successful
        ValueError  Otherwise
    '''

    token = None
    if 'Authorization' in request.headers:
        # Bearer TOKEN
        auth_header = request.headers['Authorization']
        token = auth_header.split(" ")[1] if len(auth_header.split(" ")) > 1 else None
    
    # If no token, return unauthorized
    if not token:
        raise ValueError('Authentication Token is missing!')
    
    try:
        # Decode the token
        payload = jwt.decode(token, SECRET_KEY, algorithms=['HS256'])
        return payload

    except jwt.ExpiredSignatureError:
        raise ValueError('Token has expired!')

    except jwt.InvalidTokenError:
        raise ValueError('Invalid token!')

##-Decorator
def token_required(only_admins: bool = False):
    '''
    Creates a decorator that ensure that the connected user possesses a valid token.

    In:
        - only_admins: if True, restrict access only to admins. Otherwise, restrict access to token bearers.
    '''

    def decorator(f):
        @wraps(f)
        def decorated(*args, **kwargs):
            try:
                payload = decode_token()

            except ValueError as err:
                return jsonify({'message': str(err)}), 401

            # Privilege check
            if only_admins and not payload['is_admin']:
                return jsonify({'message': 'Only admins can access this resource'}), 403

            # If we get here, token is valid
            return f(*args, **kwargs)
        
        return decorated

    return decorator

